name: Deploy Store

on:
  push:
    branches: [ master, feature/emotion-71 ]
    tags:
      - v*.*
      - test/*

  workflow_dispatch:
    input:
      loglevel:
        description: 'Log Level'
        required: true
        default: 'warning'
      name:
        description: 'Upload AAB'
        required: true
        default: 'Deploy'

jobs:
  build-release-bundle:
    name: Deploy Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        shell: bash
        run: ./gradlew bundleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app AAB
        id: sign_app
        with:
            releaseDirectory: app/build/outputs/bundle/release
            signingKeyBase64: ${{ secrets.JKS }}
            alias: ${{ secrets.ALIAS }}
            keyStorePassword: ${{ secrets.STOREPASS }}
            keyPassword: ${{ secrets.STOREPASS }}
        env:
            BUILD_TOOLS_VERSION: "30.0.3"

      - name: Google Play Store Upload
        uses: r0adkll/upload-google-play@v1
        with:
            serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
            packageName: com.teamtuna.emotionaldiary
            releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
            track: internal
#    alpha, beta, internal, production(default), internalsharing
