# This is a basic workflow to help you get started with Actions

name: develop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # 유닛 테스트
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
    
    # 빌드
    - name: Build with Gradle
      run: ./gradlew build

    # Debug APK 빌드
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
      
    # APK 업로드
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs/apk/debug
